### ISSUE TITLE
missing frankenX.xacro

### ISSUE THREAD

**Issue by nhooram** [csiro-robotics/frankenX_syropod#4]
Hi, thanks for the great work. 

I'm trying to launch the rviz config file from the main repo for frankenX, and it seems there isn't the xacro file for this.  I searched all the repos for the organization to no avail. Any pointers would be appreciated!

**Comment by benjamin-tam** [comment]
Hi Hooram,

Correct, a xacro/urdf file for frankenX hasn't been created. This repo is mainly for setting up the robot hardware as described in https://github.com/csiro-robotics/shc_tutorials and thus doesn't support gazebo/rviz. It looks like we left some old launch files/configs which are broken for frankenX. I'll have to clean it up.

If you would like to test launching rviz for OpenSHC, try out running bullet robot, https://github.com/csiro-robotics/bullet_syropod. It has the xacro/urdf and rviz/gazebo launch set up to work.

**Comment by nhooram** [comment]
Gotcha. I actually just read that it doesn't exist in the readme. Thanks!

**Comment by benjamin-tam** [comment]
#5
